import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navber from "./components/Navber";
import { AuthProvider } from "./context/auth";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Eatist",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ja">
            <head>
                <link rel="manifest" href="/manifest.json" />
            </head>
            <AuthProvider>
                <body className="h-screen w-screen">
                    <div className="">
                        <Providers>
                            <Navber />
                            {children}
                        </Providers>
                    </div>
                </body>
            </AuthProvider>
        </html>
    );
}
